---
- hosts: localhost
  become: true
  tasks:
  - name: Install java
    apt:  update_cache=yes name=openjdk-8-jdk state=present

  - name: Install maven
    apt:  name=maven state=present

  - name: ensure docker repository key is installed
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: ensure docker registry is available
    apt_repository: repo='deb https://download.docker.com/linux/ubuntu focal stable' state=present
  - name: ensure docker and dependencies are installed
    apt: name=docker-ce update_cache=yes
  - name: ensure pip is installed
    apt: name=python3-pip
  - service: name=docker state=restarted
  - name: Install Docker Module for Python
    pip:
      name: docker
